using Cocona;
using IdasCli.Mcp;
using IdasCli.Tools;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using ModelContextProtocol.Server;

public class McpServerCommand : CommandsBase
{
    [Command("serve", Description = "Start the MCP server with dynamically registered Cocona commands")]
    public async Task Serve()
    {
        // Scan and register all Cocona commands as MCP tools (suppress verbose output)
        McpToolRegistrar.ScanAndRegisterTools(verbose: false);

        var builder = Host.CreateDefaultBuilder()
            .ConfigureServices((context, services) =>
            {
                services.AddMcpServer()
                    .WithStdioServerTransport()
                    .WithToolsFromAssembly();
            })
            .ConfigureLogging(logging =>
            {
                // Disable all console logging for MCP server
                logging.ClearProviders();
            });

        await builder.Build().RunAsync();
    }

    [Command("generate-tools", Description = "Generate MCP tool source code from Cocona commands")]
    public async Task GenerateTools(
        [Option("output", Description = "Output file path")] 
        string output = "Mcp/AutoGeneratedMcpTools.cs")
    {
        await McpToolSourceGenerator.GenerateAndSaveAsync(output);
    }
}
