// <auto-generated/>
// This file is automatically generated by McpToolSourceGenerator
// DO NOT EDIT MANUALLY

#nullable disable

using System.ComponentModel;
using System.Text.Json;
using ModelContextProtocol.Server;

namespace IdasCli.Mcp;

/// <summary>
/// Auto-generated MCP tools from Cocona commands
/// </summary>
[McpServerToolType]
public class AutoGeneratedMcpTools : CommandsBase
{
    private readonly DynamicCoconaTool _executor;

    public AutoGeneratedMcpTools()
    {
        _executor = new DynamicCoconaTool(null!);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "artikel_list")]
    [Description("")]
    public async Task<object> ListArtikel()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("artikel_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "artikel_put")]
    [Description("")]
    public async Task<object> PutArtikel(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("artikel_put", parameters);
    }

    /// <summary>
    /// Create a sample KatalogArtikelDTO
    /// </summary>
    [McpServerTool(Name = "artikel_sample")]
    [Description("Create a sample KatalogArtikelDTO")]
    public async Task<object> SampleArtikel()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("artikel_sample", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "av_list")]
    [Description("")]
    public async Task<object> ListAv(
        [Description("Reset since")] DateTime? since = null
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "since", since },
        };

        return await _executor.InvokeCommand("av_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "av_get")]
    [Description("")]
    public async Task<object> GetAv(
        [Description("AVPos-GUID or PCode")] string pos
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "pos", pos },
        };

        return await _executor.InvokeCommand("av_get", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "benutzer_login")]
    [Description("")]
    public async Task<object> LoginBenutzer(
        [Description("Environment (dev, staging, produktiv)")] string env,
        [Description("Password")] string password,
        [Description("User name")] string user,
        [Description("AppGuid (provided by Gandalan)")] Guid? appGuid = null
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "user", user },
            { "password", password },
            { "appGuid", appGuid },
            { "env", env },
        };

        return await _executor.InvokeCommand("benutzer_login", parameters);
    }

    /// <summary>
    /// Get the list of own users
    /// </summary>
    [McpServerTool(Name = "benutzer_list")]
    [Description("Get the list of own users")]
    public async Task<object> ListBenutzer()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("benutzer_list", parameters);
    }

    /// <summary>
    /// Reset password for a user by email
    /// </summary>
    [McpServerTool(Name = "benutzer_password-reset")]
    [Description("Reset password for a user by email")]
    public async Task<object> PasswordResetBenutzer(
        [Description("User's email address")] string email
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "email", email },
        };

        return await _executor.InvokeCommand("benutzer_password-reset", parameters);
    }

    /// <summary>
    /// Change password for the current user
    /// </summary>
    [McpServerTool(Name = "benutzer_change-password")]
    [Description("Change password for the current user")]
    public async Task<object> ChangePasswordBenutzer(
        [Description("New password")] string newPassword,
        [Description("Current password")] string oldPassword,
        [Description("Username or email")] string username
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "username", username },
            { "oldPassword", oldPassword },
            { "newPassword", newPassword },
        };

        return await _executor.InvokeCommand("benutzer_change-password", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "gsql_list")]
    [Description("")]
    public async Task<object> ListGsql()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("gsql_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "gsql_get")]
    [Description("")]
    public async Task<object> GetGsql(
        [Description("Beleg-GUID")] Guid beleg
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "beleg", beleg },
        };

        return await _executor.InvokeCommand("gsql_get", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "gsql_reset")]
    [Description("")]
    public async Task<object> ResetGsql(
        [Description("Reset since")] DateTime since
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "since", since },
        };

        return await _executor.InvokeCommand("gsql_reset", parameters);
    }

    /// <summary>
    /// Get all configuration sets
    /// </summary>
    [McpServerTool(Name = "konfigsatz_list")]
    [Description("Get all configuration sets")]
    public async Task<object> ListKonfigsatz()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("konfigsatz_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "konfigsatz_put")]
    [Description("")]
    public async Task<object> PutKonfigsatz(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("konfigsatz_put", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "kontakt_list")]
    [Description("")]
    public async Task<object> ListKontakt()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("kontakt_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "kontakt_get")]
    [Description("")]
    public async Task<object> GetKontakt(
        [Description("Kontakt-GUID")] Guid kontakt
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "kontakt", kontakt },
        };

        return await _executor.InvokeCommand("kontakt_get", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "kontakt_put")]
    [Description("")]
    public async Task<object> PutKontakt(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("kontakt_put", parameters);
    }

    /// <summary>
    /// Create a sample KontaktDTO
    /// </summary>
    [McpServerTool(Name = "kontakt_sample")]
    [Description("Create a sample KontaktDTO")]
    public async Task<object> SampleKontakt()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("kontakt_sample", parameters);
    }

    /// <summary>
    /// Get the inventory list
    /// </summary>
    [McpServerTool(Name = "lagerbestand_list")]
    [Description("Get the inventory list")]
    public async Task<object> ListLagerbestand(
        [Description("Reset since")] DateTime? since = null
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "since", since },
        };

        return await _executor.InvokeCommand("lagerbestand_list", parameters);
    }

    /// <summary>
    /// Get the booking list
    /// </summary>
    [McpServerTool(Name = "lagerbuchung_list")]
    [Description("Get the booking list")]
    public async Task<object> ListLagerbuchung(
        [Description("Start date of booking list")] DateTime from,
        [Description("End date for booking list")] DateTime till
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "from", from },
            { "till", till },
        };

        return await _executor.InvokeCommand("lagerbuchung_list", parameters);
    }

    /// <summary>
    /// Book inventory
    /// </summary>
    [McpServerTool(Name = "lagerbuchung_put")]
    [Description("Book inventory")]
    public async Task<object> PutLagerbuchung(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("lagerbuchung_put", parameters);
    }

    /// <summary>
    /// Create a sample LagerbuchungDTO
    /// </summary>
    [McpServerTool(Name = "lagerbuchung_sample")]
    [Description("Create a sample LagerbuchungDTO")]
    public async Task<object> SampleLagerbuchung()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("lagerbuchung_sample", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "rollen_listrollen")]
    [Description("")]
    public async Task<object> ListrollenRollen()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("rollen_listrollen", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "serie_list")]
    [Description("")]
    public async Task<object> ListSerie()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("serie_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "serie_get")]
    [Description("")]
    public async Task<object> GetSerie(
        [Description("Serie-GUID")] Guid serie
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "serie", serie },
        };

        return await _executor.InvokeCommand("serie_get", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "serie_put")]
    [Description("")]
    public async Task<object> PutSerie(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("serie_put", parameters);
    }

    /// <summary>
    /// Create a sample SerieDTO
    /// </summary>
    [McpServerTool(Name = "serie_sample")]
    [Description("Create a sample SerieDTO")]
    public async Task<object> SampleSerie()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("serie_sample", parameters);
    }

    /// <summary>
    /// Get all UI definitions
    /// </summary>
    [McpServerTool(Name = "uidefinition_list")]
    [Description("Get all UI definitions")]
    public async Task<object> ListUidefinition()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("uidefinition_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "uidefinition_get")]
    [Description("")]
    public async Task<object> GetUidefinition(
        [Description("UIDefinition GUID")] Guid guid
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "guid", guid },
        };

        return await _executor.InvokeCommand("uidefinition_get", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "uidefinition_put")]
    [Description("")]
    public async Task<object> PutUidefinition(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("uidefinition_put", parameters);
    }

    /// <summary>
    /// Get all variants
    /// </summary>
    [McpServerTool(Name = "variante_list")]
    [Description("Get all variants")]
    public async Task<object> ListVariante()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("variante_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "variante_get")]
    [Description("")]
    public async Task<object> GetVariante(
        [Description("Variante GUID")] Guid guid,
        [Description("Include configurations")] bool? includeKonfigs = true,
        [Description("Include UI definitions")] bool? includeUIDefs = true
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "guid", guid },
            { "includeUIDefs", includeUIDefs },
            { "includeKonfigs", includeKonfigs },
        };

        return await _executor.InvokeCommand("variante_get", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "variante_put")]
    [Description("")]
    public async Task<object> PutVariante(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("variante_put", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "variante_guids")]
    [Description("")]
    public async Task<object> GuidsVariante()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("variante_guids", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "vorgang_list")]
    [Description("")]
    public async Task<object> ListVorgang(
        [Description("Include archived Vorgänge")] bool? includeArchive = false,
        [Description("Year to list")] int? jahr = null
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jahr", jahr },
            { "includeArchive", includeArchive },
        };

        return await _executor.InvokeCommand("vorgang_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "vorgang_get")]
    [Description("")]
    public async Task<object> GetVorgang(
        [Description("Vorgang-GUID")] Guid vorgang
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "vorgang", vorgang },
        };

        return await _executor.InvokeCommand("vorgang_get", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "vorgang_put")]
    [Description("")]
    public async Task<object> PutVorgang(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("vorgang_put", parameters);
    }

    /// <summary>
    /// Create a sample VorgangDTO
    /// </summary>
    [McpServerTool(Name = "vorgang_sample")]
    [Description("Create a sample VorgangDTO")]
    public async Task<object> SampleVorgang()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("vorgang_sample", parameters);
    }

    /// <summary>
    /// Archiviert einen einzelnen Vorgang
    /// </summary>
    [McpServerTool(Name = "vorgang_archive")]
    [Description("Archiviert einen einzelnen Vorgang")]
    public async Task<object> ArchiveVorgang(
        [Description("Vorgang-GUID")] Guid vorgang
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "vorgang", vorgang },
        };

        return await _executor.InvokeCommand("vorgang_archive", parameters);
    }

    /// <summary>
    /// Archiviert mehrere Vorgänge gleichzeitig
    /// </summary>
    [McpServerTool(Name = "vorgang_archive-bulk")]
    [Description("Archiviert mehrere Vorgänge gleichzeitig")]
    public async Task<object> ArchiveBulkVorgang(
        [Description("Kommagetrennte Liste von Vorgang-GUIDs")] string vorgaenge
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "vorgaenge", vorgaenge },
        };

        return await _executor.InvokeCommand("vorgang_archive-bulk", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "vorgang_activate")]
    [Description("")]
    public async Task<object> ActivateVorgang(
        [Description("Vorgang-GUID")] Guid vorgang
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "vorgang", vorgang },
        };

        return await _executor.InvokeCommand("vorgang_activate", parameters);
    }

    /// <summary>
    /// Get the list of product groups, including all their products
    /// </summary>
    [McpServerTool(Name = "warengruppe_list")]
    [Description("Get the list of product groups, including all their products")]
    public async Task<object> ListWarengruppe()
    {
        var parameters = new Dictionary<string, object?>
        {
        };

        return await _executor.InvokeCommand("warengruppe_list", parameters);
    }

    /// <summary>
    /// Get all value lists
    /// </summary>
    [McpServerTool(Name = "werteliste_list")]
    [Description("Get all value lists")]
    public async Task<object> ListWerteliste(
        [Description("Include auto-generated value lists")] bool? includeAuto = true
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "includeAuto", includeAuto },
        };

        return await _executor.InvokeCommand("werteliste_list", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "werteliste_get")]
    [Description("")]
    public async Task<object> GetWerteliste(
        [Description("Werteliste GUID")] Guid guid,
        [Description("Include auto-generated value lists")] bool? includeAuto = true
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "guid", guid },
            { "includeAuto", includeAuto },
        };

        return await _executor.InvokeCommand("werteliste_get", parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    [McpServerTool(Name = "werteliste_put")]
    [Description("")]
    public async Task<object> PutWerteliste(
        [Description("JSON string containing the data")] string jsonContent
    )
    {
        var parameters = new Dictionary<string, object?>
        {
            { "jsonContent", jsonContent },
        };

        return await _executor.InvokeCommand("werteliste_put", parameters);
    }

}
